import { fileURLToPath } from "node:url";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup.ts"],
    // `supabase/` is included so the script ⇄ migration sync guard can live next
    // to the SQL files it protects (coverage still only measures `src/`).
    include: ["src/**/*.{test,spec}.{ts,tsx}", "supabase/**/*.{test,spec}.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.{test,spec}.{ts,tsx}",
        "src/components/ui/**", // vendored shadcn/ui components
        "src/lib/supabase/database.types.ts", // generated by supabase gen types
        "**/*.d.ts",
        "**/*.config.*",
        "e2e/**",
      ],
      // Coverage ratchet: thresholds sit just below the measured baseline
      // (2026-07) so a regression fails CI, without inventing numbers that fail
      // today. Global is low because app/UI components are untested by design;
      // the well-tested logic in src/lib and src/services is ratcheted tighter.
      thresholds: {
        // Global floor. Measured: 15.73% lines/statements, 21.9% functions, 43.35% branches.
        lines: 15,
        statements: 15,
        functions: 20,
        branches: 42,
        // Measured: 35.01% lines/statements, 42.1% functions, 68.75% branches.
        "src/lib/**": { lines: 34, statements: 34, functions: 40, branches: 66 },
        // Measured: 41.58% lines/statements, 40% functions, 75% branches.
        "src/services/**": { lines: 40, statements: 40, functions: 38, branches: 73 },
      },
    },
  },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
});
