import { describe, expect, it } from "vitest";

import type { BiPostRow } from "@/services/analytics";
import { availablePeriods, parseReportPeriod } from "@/services/client-report";

import { reportPeriodHref, scopeCaption } from "./report-period-picker";

// ─────────────────────────────────────────────────────────────────────────────
// THE ROUND TRIP.
//
// The period is encoded here (the picker writes a URL) and decoded over in
// client-report.ts (`parseReportPeriod` reads the search param). Two files, two
// authors, one contract — and nothing held them together, which is exactly how
// "All time" came to be unreachable: the picker stripped the param to keep the
// default URL tidy, and the server cannot tell a stripped param from a first
// visit, so it resolved to the newest month instead.
//
// This test closes the loop. It drives the REAL encoder, extracts the param the
// way a browser and Next would, and feeds it to the REAL decoder. Nothing about
// the encoding is reimplemented here — a test that restates what it is testing
// would have passed happily throughout the bug.
// ─────────────────────────────────────────────────────────────────────────────

const PATHNAME = "/clients/8f3c/report";
/** Only used to make the relative href parseable; never navigated to. */
const ORIGIN = "https://arcbase.test";

function row(estimated_post_date: string): BiPostRow {
  return {
    client_id: "c1",
    client_name: "Bryan Wish",
    linkedin_post_id: `p-${estimated_post_date}`,
    post_url: null,
    post_content: null,
    post_age: null,
    estimated_post_date,
    impressions: 0,
    likes: 0,
    comments: 0,
    reposts: 0,
    saves: 0,
    interactions: 0,
    provided_engagement_rate: null,
    calculated_engagement_rate: null,
    scraped_at: null,
    uploaded_at: null,
  };
}

// Generated by the REAL `availablePeriods`, not hand-written, so a period kind
// added later is covered by the round trip automatically.
const PERIODS = availablePeriods([row("2026-07-10"), row("2026-06-10"), row("2025-01-15")]);

/** What an RSC receives: the decoded value, or `undefined` when absent. */
function paramFromHref(href: string): string | undefined {
  return new URL(href, ORIGIN).searchParams.get("period") ?? undefined;
}

describe("period URL round trip (picker encodes → client-report decodes)", () => {
  it("offers every period kind, so the round trip below cannot pass vacuously", () => {
    expect(new Set(PERIODS.map((p) => p.kind))).toEqual(
      new Set(["all", "year", "quarter", "month"]),
    );
    expect(PERIODS.filter((p) => p.kind === "month").length).toBeGreaterThanOrEqual(2);
  });

  it.each(PERIODS.map((period) => [period.key, period] as const))(
    "%s survives encode → decode unchanged",
    (_key, period) => {
      const encoded = paramFromHref(reportPeriodHref(PATHNAME, period.key));

      expect(parseReportPeriod(encoded, PERIODS)).toEqual(period);
    },
  );

  it("always writes the param, so the server can tell a choice from a first visit", () => {
    // The all-time case is the whole point: stripping the param here is
    // indistinguishable from never having chosen, and the decoder is right to
    // read that as "newest month".
    expect(paramFromHref(reportPeriodHref(PATHNAME, "all"))).toBe("all");
    expect(paramFromHref(reportPeriodHref(PATHNAME, "2026-Q3"))).toBe("2026-Q3");
  });

  it("still defaults to the newest month when no param is present at all", () => {
    // client-tabs.tsx links to the report with no param and relies on this, so
    // the fix above must not have traded one broken path for another.
    expect(parseReportPeriod(undefined, PERIODS).key).toBe("2026-07");
  });
});

describe("scopeCaption", () => {
  // Asserted as a PROPERTY — "the label survives intact" — rather than by
  // rebuilding the expected string, which would restate the implementation and
  // pass under any casing the implementation happened to apply.
  it.each(PERIODS.filter((p) => p.kind !== "all").map((p) => [p.key, p] as const))(
    "%s keeps its label's casing — a month or quarter is a proper noun",
    (_key, period) => {
      expect(scopeCaption(period)).toContain(period.label);
    },
  );

  it("lowercases only all-time, which is ordinary prose rather than a name", () => {
    const allTime = PERIODS.find((p) => p.kind === "all")!;

    expect(scopeCaption(allTime)).toBe("Scoped to all time");
  });

  it("captions every period the picker can offer", () => {
    // A period kind added later gets a caption or fails here — it cannot slip
    // through captionless.
    for (const period of PERIODS) {
      expect(scopeCaption(period)).toMatch(/^Scoped to \S/);
    }
  });
});
